### ISSUE TITLE
More Info

### ISSUE THREAD

**Issue by garudaonekh** [griffincorriher/work#2]
Please provide more info. How this code work and component required

Thank

**Comment by griffincorriher** [comment]
The level sensor uses a jsn-sr04t as the ultrasonic sensor to get the distance from the sensor the to top of the water. That distance is then converted into gallons and subtracted from an empty tank (from bottom of tank to sensor). That will give you the total gallons of liquid in the tank. It then uses a median filter to get rid of any spikes from the ultrasonic sensor, and is displayed on an LCD.

**Comment by garudaonekh** [comment]
ok, i know this sensor but it has nothing to do with chlorine as mentioned in your project title

**Comment by griffincorriher** [comment]
I think you misunderstand what this does, it measures the height of a liquid in a tank, not the amount of chlorine in water. I am measuring a tank that stores concentrated chlorine and displaying it on an lcd
